apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hackscore-claudecode-worker
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # Execution environment (gen2) - Revisionレベルで設定
        run.googleapis.com/execution-environment: gen2
        # Timeout for processing (5 minutes)
        run.googleapis.com/timeout: "300s"
        # Memory allocation
        run.googleapis.com/memory: "2Gi"
        # CPU allocation
        run.googleapis.com/cpu: "1000m"
        # Max instances
        autoscaling.knative.dev/maxScale: "10"
        # Min instances (0 for cost efficiency)
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
        - image: asia-northeast1-docker.pkg.dev/hackscore-ai-production/hackscore-repo/hackscore-claudecode-worker:latest
          ports:
            - containerPort: 8080
          env:
            # Supabase Configuration
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-url
                  key: latest
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-service-role-key
                  key: latest

            # Server Configuration
            - name: NODE_ENV
              value: "production"
            - name: DEPLOY_VERSION
              value: "v1.0.1"

            # Authentication
            - name: CLOUD_RUN_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloud-run-auth-token
                  key: latest

            # Processing Configuration
            - name: MAX_TURNS_PER_ANALYSIS
              value: "50"
            - name: ANALYSIS_TIMEOUT_MS
              value: "300000"

            # Logging
            - name: LOG_LEVEL
              value: "info"

            # Cost Management
            - name: ESTIMATED_COST_PER_TOKEN
              value: "0.000003"

          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"
