apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hackscore-claudecode-worker
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Timeout for processing (5 minutes)
        run.googleapis.com/timeout: "300s"
        # Memory allocation
        run.googleapis.com/memory: "2Gi"
        # CPU allocation
        run.googleapis.com/cpu: "1000m"
        # Max instances
        autoscaling.knative.dev/maxScale: "10"
        # Min instances (0 for cost efficiency)
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/hackscore-claudecode-worker
        ports:
        - containerPort: 8080
        env:
        # Supabase Configuration
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: hackscore-secrets
              key: SUPABASE_URL
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: hackscore-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        
        # Server Configuration
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        
        # Authentication
        - name: CLOUD_RUN_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: hackscore-secrets
              key: CLOUD_RUN_AUTH_TOKEN
        
        # Processing Configuration
        - name: MAX_TURNS_PER_ANALYSIS
          value: "50"
        - name: ANALYSIS_TIMEOUT_MS
          value: "300000"
        
        # Logging
        - name: LOG_LEVEL
          value: "info"
        
        # Cost Management
        - name: ESTIMATED_COST_PER_TOKEN
          value: "0.000003"
        
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"