apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hackscore-claudecode-worker
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # Execution environment (gen2) - Revisionレベルで設定
        run.googleapis.com/execution-environment: gen2
        # Timeout for processing (60 minutes - Cloud Run maximum)
        run.googleapis.com/timeout: "3600s"
        # Memory allocation
        run.googleapis.com/memory: "4Gi"
        # CPU allocation
        run.googleapis.com/cpu: "2000m"
        # Max instances
        autoscaling.knative.dev/maxScale: "10"
        # Min instances (0 for cost efficiency)
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 3600
      containers:
        - image: asia-northeast1-docker.pkg.dev/hackscore-ai-production/hackscore-repo/hackscore-claudecode-worker:latest
          ports:
            - containerPort: 8080
          env:
            # Supabase Configuration
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-url
                  key: latest
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-service-role-key
                  key: latest

            # Server Configuration
            - name: NODE_ENV
              value: "production"
            - name: DEPLOY_VERSION
              value: "v1.0.1"

            # Authentication
            - name: CLOUD_RUN_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloud-run-auth-token
                  key: latest

            # Processing Configuration
            - name: MAX_TURNS_PER_ANALYSIS
              value: "205"
            - name: ANALYSIS_TIMEOUT_MS
              value: "3300000"

            # Logging
            - name: LOG_LEVEL
              value: "info"

            # Cost Management
            - name: ESTIMATED_COST_PER_TOKEN
              value: "0.000003"

            # Node.js and npm Configuration for Claude Code SDK
            - name: NPM_CONFIG_PREFIX
              value: "/tmp/.npm-global"
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/.npm-global/bin"
            - name: HOME
              value: "/tmp"
            - name: TMPDIR
              value: "/tmp"
            - name: NPM_CONFIG_CACHE
              value: "/tmp/.npm"
            - name: NPM_CONFIG_UNSAFE_PERM
              value: "true"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
            - name: XDG_CONFIG_HOME
              value: "/tmp/.config"

          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
            requests:
              memory: "2Gi"
              cpu: "1000m"
